# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308e67365d4b2a5373657707ac6e08d28312096eeb6fe07de2ff5387b1b7a8ae8878168f65a44b5eb61fe600dfcce31cbd909b9db65f301f0ca36856a75b20e0

test:
  secret_key_base: a4384606a71a8ec4c4bd93cdfe121c97531bc707d4a63e777cd724eb8c152550ecc9777e4a7ced6cfd10eb2816953da9916160ec21e7653a3c6afb6c21349c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
